/* tslint:disable */
/* eslint-disable */
/**
 * Temporary stub types — regenerated by Payload on first successful boot.
 * Run `npm run generate:types` after admin starts to refresh.
 */

export interface User {
  id: number | string
  email: string
  name?: string | null
  updatedAt: string
  createdAt: string
}

export interface Media {
  id: number | string
  alt: string
  url?: string | null
  updatedAt: string
  createdAt: string
}

export interface Trip {
  id: number | string
  name: string
  description?: string | null
  durationHours: number
  price1: number
  price2: number
  deposit: number
  active?: boolean | null
  sortOrder?: number | null
  updatedAt: string
  createdAt: string
}

export interface Booking {
  id: number | string
  entryKind?: 'booking' | 'block' | null
  trip?: (number | string) | Trip | null
  bookingDate: string
  blockEndDate?: string | null
  bookingTime: string
  reservationEndTime?: string | null
  durationHours: number
  drivers: number
  passengers: number
  people?: number | null
  customerFirstName?: string | null
  customerLastName?: string | null
  customerPhone: string
  customerEmail?: string | null
  customerNotes?: string | null
  source: 'website' | 'manual_admin' | 'phone' | 'google_calendar'
  status: 'pending' | 'confirmed' | 'cancelled' | 'expired' | 'deposit_paid'
  fullPrice?: number | null
  depositAmount?: number | null
  remainingAmount?: number | null
  paymentStatus?: 'unpaid' | 'deposit_paid' | 'paid' | 'refunded' | null
  paymentMethod?: 'online' | 'cash' | 'transfer' | 'card_onsite' | 'blik' | null
  cashbillPaymentId?: string | null
  cashbillChannel?: string | null
  sessionId?: string | null
  gcalEventId?: string | null
  confirmationEmailSentAt?: string | null
  expiresAt?: string | null
  updatedAt: string
  createdAt: string
}

export interface BookingSetting {
  id: number | string
  totalQuads: number
  openHour: number
  closeHour: number
  minBookingLeadHours: number
  holdMinutes: number
  cashbillLiveEnabled?: boolean | null
  cashbillShopId?: string | null
  cashbillSecret?: string | null
  gcalCalendarId?: string | null
  gcalServiceAccountJson?: string | null
  updatedAt: string
  createdAt: string
}

export interface Config {
  collections: {
    users: User
    media: Media
    trips: Trip
    bookings: Booking
  }
  globals: {
    'booking-settings': BookingSetting
  }
}
